[package]
name = "bitflags2"
version = "0.3.1"
edition = "2024"
description = "Derive-like bitflags powered by an attribute macro"
readme = "README.md"
license = "MIT"
authors = ["cet"]
repository = "https://github.com/cet-t/bitflags2"

[lib]
crate-type = ["rlib"]

[features]
serde = ["dep:serde"]

[dependencies]
bitflags2-derive = { version = "0.2.2", path = "bitflags2-derive" }
serde = { version = "1", optional = true, features = ["derive"] }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
