[package]
name = "bitflags2"
version = "0.1.0"
edition = "2024"
description = "Derive-like bitflags powered by an attribute macro"
license = "MIT"
authors = ["cet"]
repository = "https://github.com/cet-t/bitflags2"

[lib]
crate-type = ["rlib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
bitflags2-derive = { version = "0.1.0", path = "bitflags2-derive" }
